services:
  db:
    image: mysql:8.0
    container_name: carbon-mysql
    env_file: .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - carbonmanager_net

  migrator:
    build:
      context: .
      dockerfile: database/Dockerfile
    depends_on:
      db:
        condition: service_healthy	
    env_file: .env
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - ./database:/app/database
    restart: "no"
    networks:
      - carbonmanager_net

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: carbon-backend
    depends_on:
      db:
        condition: service_healthy
      migrator:
         condition: service_completed_successfully
    env_file: .env
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
      # - ./scripts:/app/scripts
    command: ["python", "run.py"]
    restart: unless-stopped
    networks:
      - carbonmanager_net

  chain-service:
    build:
      context: ./chain-service
      dockerfile: Dockerfile
    container_name: carbon-chain
    env_file: ./chain-service/.env
    ports:
      - "3001:3001"
    volumes:
      - ./chain-service/src:/app/src
    command: ["npm","start"]
    restart: unless-stopped
    networks:
      - shared-net
      - carbonmanager_net

volumes:
  mysql_data:

networks:
  shared-net:
    external: true
  carbonmanager_net:
    name: carbonmanager_net
    driver: bridge

